# Generated by Django 3.1.1 on 2020-10-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='user/profile_img/')),
                ('mobile', models.IntegerField(max_length=12)),
                ('emailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.admin_login')),
            ],
        ),
    ]
