# Generated by Django 3.1.1 on 2020-10-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201008_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(upload_to='profile_img'),
        ),
    ]
