# Generated by Django 3.1.1 on 2020-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201008_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindata',
            name='emailid',
        ),
        migrations.AddField(
            model_name='admindata',
            name='rollno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rollno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=50),
        ),
    ]
